{
  description = ''Autogenerated glew bindings for Nim'';

  inputs.flakeNimbleLib.owner = "riinr";
  inputs.flakeNimbleLib.ref   = "master";
  inputs.flakeNimbleLib.repo  = "nim-flakes-lib";
  inputs.flakeNimbleLib.type  = "github";
  inputs.flakeNimbleLib.inputs.nixpkgs.follows = "nixpkgs";
  
  inputs.src-glew-master.flake = false;
  inputs.src-glew-master.ref   = "refs/heads/master";
  inputs.src-glew-master.owner = "jyapayne";
  inputs.src-glew-master.repo  = "nim-glew";
  inputs.src-glew-master.type  = "github";
  
  inputs."github-jyapayne-nimterop".owner = "nim-nix-pkgs";
  inputs."github-jyapayne-nimterop".ref   = "master";
  inputs."github-jyapayne-nimterop".repo  = "github-jyapayne-nimterop";
  inputs."github-jyapayne-nimterop".dir   = "v0_4_4";
  inputs."github-jyapayne-nimterop".type  = "github";
  inputs."github-jyapayne-nimterop".inputs.nixpkgs.follows = "nixpkgs";
  inputs."github-jyapayne-nimterop".inputs.flakeNimbleLib.follows = "flakeNimbleLib";
  
  inputs."github-jyapayne-nim-glfw".owner = "nim-nix-pkgs";
  inputs."github-jyapayne-nim-glfw".ref   = "master";
  inputs."github-jyapayne-nim-glfw".repo  = "github-jyapayne-nim-glfw";
  inputs."github-jyapayne-nim-glfw".dir   = "master";
  inputs."github-jyapayne-nim-glfw".type  = "github";
  inputs."github-jyapayne-nim-glfw".inputs.nixpkgs.follows = "nixpkgs";
  inputs."github-jyapayne-nim-glfw".inputs.flakeNimbleLib.follows = "flakeNimbleLib";
  
  outputs = { self, nixpkgs, flakeNimbleLib, ...}@deps:
  let 
    lib  = flakeNimbleLib.lib;
    args = ["self" "nixpkgs" "flakeNimbleLib" "src-glew-master"];
    over = if builtins.pathExists ./override.nix 
           then { override = import ./override.nix; }
           else { };
  in lib.mkRefOutput (over // {
    inherit self nixpkgs ;
    src  = deps."src-glew-master";
    deps = builtins.removeAttrs deps args;
    meta = builtins.fromJSON (builtins.readFile ./meta.json);
  } );
}