# aditional handmade info


tasks = ["test"]

[submodules.csources]
path = "bearssl/csources"
url  = "https://github.com/status-im/BearSSL"
ref  = "46f7dddce75227f2e40ab94d66ceb9f19ee6b1b0"  # todo think how to keep it updated
