{
  description = ''SDL2 Autogenerated wrapper'';

  inputs.flakeNimbleLib.owner = "riinr";
  inputs.flakeNimbleLib.ref   = "master";
  inputs.flakeNimbleLib.repo  = "nim-flakes-lib";
  inputs.flakeNimbleLib.type  = "github";
  inputs.flakeNimbleLib.inputs.nixpkgs.follows = "nixpkgs";
  
  inputs."sdl2-master".dir   = "master";
  inputs."sdl2-master".owner = "nim-nix-pkgs";
  inputs."sdl2-master".ref   = "master";
  inputs."sdl2-master".repo  = "sdl2";
  inputs."sdl2-master".type  = "github";
  inputs."sdl2-master".inputs.nixpkgs.follows = "nixpkgs";
  inputs."sdl2-master".inputs.flakeNimbleLib.follows = "flakeNimbleLib";
  
  outputs = { self, nixpkgs, flakeNimbleLib, ...}@inputs:
  let 
    lib  = flakeNimbleLib.lib;
    args = ["self" "nixpkgs" "flakeNimbleLib"];
  in lib.mkProjectOutput {
    inherit self nixpkgs;
    meta = builtins.fromJSON (builtins.readFile ./meta.json);
    refs = builtins.removeAttrs inputs args;
  };
}