graph NimPkgs;
    binance-->binance;
    ;
    ur-->ur;
    ;
    jwt-->jwt;
    ;
    nimssh2-->nimssh2;
    ;
    switch_build-->switch_build;
    ;
    nimrax-->nimrax;
    ;
    nimsha2-->nimsha2;
    ;
    googleapi-->googleapi;
    ;
    uuids-->uuids;
    ;
    clibpp-->clibpp;
    ;
    lilt-->lilt;
    ;
    ansiparse-->ansiparse;
    ;
    gh_nimrod_doc_pages-->gh_nimrod_doc_pages;
    ;
    jhash-->jhash;
    ;
    tic80-->tic80;
    ;
    isaac-->isaac;
    ;
    nimislides-->nimislides;
    ;
    anttweakbar-->anttweakbar;
    ;
    fuzzy-->fuzzy;
    ;
    react16-->react16;
    ;
    highlight-->highlight;
    ;
    matsuri-->matsuri;
    ;
    nimpari-->nimpari;
    ;
    openal-->openal;
    ;
    markx-->markx;
    ;
    hackpad-->hackpad;
    ;
    nephyr-->nephyr;
    ;
    toktok-->toktok;
    ;
    nimeverything-->nimeverything;
    ;
    resultutils-->resultutils;
    ;
    stdarg-->stdarg;
    ;
    otplib-->otplib;
    ;
    cloudbet-->cloudbet;
    ;
    des-->des;
    ;
    nimvisa-->nimvisa;
    ;
    decimal128-->decimal128;
    ;
    telenim-->telenim;
    ;
    mathexpr-->mathexpr;
    ;
    kexpr-->kexpr;
    ;
    nanoid-->nanoid;
    ;
    sdf-->sdf;
    ;
    vec-->vec;
    ;
    nettest-->nettest;
    ;
    rdgui-->rdgui;
    ;
    names-->names;
    ;
    stripe-->stripe;
    ;
    uri3-->uri3;
    ;
    lz77-->lz77;
    ;
    mctranslog-->mctranslog;
    ;
    serialization-->serialization;
    ;
    skybook-->skybook;
    ;
    spurdify-->spurdify;
    ;
    strunicode-->strunicode;
    ;
    circleci_client-->circleci_client;
    ;
    redpool-->redpool;
    ;
    mycouch-->mycouch;
    ;
    torch-->torch;
    ;
    moustachu-->moustachu;
    ;
    fasttext-->fasttext;
    ;
    fragments-->fragments;
    ;
    pararules-->pararules;
    ;
    winserial-->winserial;
    ;
    matrixsdk-->matrixsdk;
    ;
    mcu_utils-->mcu_utils;
    ;
    rx_nim-->rx_nim;
    ;
    libcurl-->libcurl;
    ;
    nimlua-->nimlua;
    ;
    pythonfile-->pythonfile;
    ;
    opencl-->opencl;
    ;
    readfq-->readfq;
    ;
    nordaudio-->nordaudio;
    ;
    ringdeque-->ringdeque;
    ;
    nimfuzzy-->nimfuzzy;
    ;
    globby-->globby;
    ;
    gplay-->gplay;
    ;
    bytesequtils-->bytesequtils;
    ;
    mangle-->mangle;
    ;
    mike-->mike;
    ;
    avbin-->avbin;
    ;
    njo-->njo;
    ;
    listenbrainz-->listenbrainz;
    ;
    bitstreams-->bitstreams;
    ;
    wxnim-->wxnim;
    ;
    bitset-->bitset;
    ;
    freeimage-->freeimage;
    ;
    mongopool-->mongopool;
    ;
    github-iffy-nim-dbus-->github-iffy-nim-dbus;
    ;
    pinggraph-->pinggraph;
    ;
    io-myo-->io-myo;
    ;
    bearlibterminal-->bearlibterminal;
    ;
    spills-->spills;
    ;
    gradient-->gradient;
    ;
    stalinsort-->stalinsort;
    ;
    ballpark-->ballpark;
    ;
    libsaedea-->libsaedea;
    ;
    html_tools-->html_tools;
    ;
    sss-->sss;
    ;
    inumon-->inumon;
    ;
    aglet-->aglet;
    ;
    nimtess2-->nimtess2;
    ;
    libplist-->libplist;
    ;
    github-zacharycarter-bgfxextrasdotnim-->github-zacharycarter-bgfxextrasdotnim;
    ;
    bncurve-->bncurve;
    ;
    gtk2-->gtk2;
    ;
    nimchromepath-->nimchromepath;
    ;
    spryvm-->spryvm;
    ;
    subexes-->subexes;
    ;
    vkapi-->vkapi;
    ;
    nimbench-->nimbench;
    ;
    polynumeric-->polynumeric;
    ;
    klymene-->klymene;
    ;
    entoody-->entoody;
    ;
    anano-->anano;
    ;
    numericalnim-->numericalnim;
    ;
    vscds-->vscds;
    ;
    zmq-->zmq;
    ;
    chebyshev-->chebyshev;
    ;
    contracts-->contracts;
    ;
    iterrr-->iterrr;
    ;
    oldwinapi-->oldwinapi;
    ;
    web3-->web3;
    ;
    shioridll-->shioridll;
    ;
    bitarray-->bitarray;
    ;
    ensem-->ensem;
    ;
    fidgetty-->fidgetty;
    ;
    gurl-->gurl;
    ;
    patgraph-->patgraph;
    ;
    tradingview-->tradingview;
    ;
    taps-->taps;
    ;
    biblioteca_guarrilla-->biblioteca_guarrilla;
    ;
    nimbug-->nimbug;
    ;
    msgpack4nim-->msgpack4nim;
    ;
    nanovg-->nanovg;
    ;
    csv2json-->csv2json;
    ;
    genny-->genny;
    ;
    minhook-->minhook;
    ;
    nimterlingua-->nimterlingua;
    ;
    autome-->autome;
    ;
    sha1ext-->sha1ext;
    ;
    libkeepass-->libkeepass;
    ;
    qeu-->qeu;
    ;
    userdef-->userdef;
    ;
    nimfunge98-->nimfunge98;
    ;
    surfing-->surfing;
    ;
    cli_menu-->cli_menu;
    ;
    nmi-->nmi;
    ;
    libusb-->libusb;
    ;
    opussum-->opussum;
    ;
    questionable-->questionable;
    ;
    ethers-->ethers;
    ;
    lazyseq-->lazyseq;
    ;
    stacks-->stacks;
    ;
    arturo-->arturo;
    ;
    ppm-->ppm;
    ;
    googlesearch-->googlesearch;
    ;
    host-->host;
    ;
    nimwin-->nimwin;
    ;
    animatecss-->animatecss;
    ;
    timerwheel-->timerwheel;
    ;
    consul-->consul;
    ;
    glfw-->glfw;
    ;
    nimpress-->nimpress;
    ;
    onnxruntime-->onnxruntime;
    ;
    termui-->termui;
    ;
    sbttl-->sbttl;
    ;
    ski-->ski;
    ;
    picohttpparser-->picohttpparser;
    ;
    binstreams-->binstreams;
    ;
    gimei-->gimei;
    ;
    nimcfitsio-->nimcfitsio;
    ;
    package_visible_types-->package_visible_types;
    ;
    treesitter_css-->treesitter_css;
    ;
    libfswatch-->libfswatch;
    ;
    importc_helpers-->importc_helpers;
    ;
    statistical_tests-->statistical_tests;
    ;
    optionals-->optionals;
    ;
    rfc3339-->rfc3339;
    ;
    tsv2json-->tsv2json;
    ;
    easings-->easings;
    ;
    weave-->weave;
    ;
    urlon-->urlon;
    ;
    loadenv-->loadenv;
    ;
    nimnews-->nimnews;
    ;
    nimfasttext-->nimfasttext;
    ;
    nimpmda-->nimpmda;
    ;
    combparser-->combparser;
    ;
    azure_translate-->azure_translate;
    ;
    nim-nmap-->nim-nmap;
    ;
    fswatch-->fswatch;
    ;
    linear_models-->linear_models;
    ;
    libclang-->libclang;
    ;
    nwatchdog-->nwatchdog;
    ;
    treesitter_go-->treesitter_go;
    ;
    zws-->zws;
    ;
    xevloop-->xevloop;
    ;
    sim-->sim;
    ;
    memlib-->memlib;
    ;
    nimrun-->nimrun;
    ;
    distorm3-->distorm3;
    ;
    uncomment-->uncomment;
    ;
    syscall-->syscall;
    ;
    ngtcp2-->ngtcp2;
    ;
    nimlevenshtein-->nimlevenshtein;
    ;
    memviews-->memviews;
    ;
    aria-->aria;
    ;
    nim_exodus-->nim_exodus;
    ;
    fugitive-->fugitive;
    ;
    huenim-->huenim;
    ;
    anonimongo-->anonimongo;
    ;
    ggplotnim-->ggplotnim;
    ;
    openssl_evp-->openssl_evp;
    ;
    imgcat-->imgcat;
    ;
    nimjl-->nimjl;
    ;
    openexchangerates-->openexchangerates;
    ;
    pwd-->pwd;
    ;
    ytextractor-->ytextractor;
    ;
    prometheus-->prometheus;
    ;
    asyncpythonfile-->asyncpythonfile;
    ;
    linuxfb-->linuxfb;
    ;
    laser-->laser;
    ;
    graphemes-->graphemes;
    ;
    nimactors-->nimactors;
    ;
    nimkerberos-->nimkerberos;
    ;
    csfml-->csfml;
    ;
    nimr-->nimr;
    ;
    sdl2-->sdl2;
    ;
    nimothello-->nimothello;
    ;
    applicates-->applicates;
    ;
    looper-->looper;
    ;
    chacha20-->chacha20;
    ;
    firejail-->firejail;
    ;
    osutil-->osutil;
    ;
    todoist-->todoist;
    ;
    libjwt-->libjwt;
    ;
    prologue-->prologue;
    ;
    github-yglukhov-clurp-->github-yglukhov-clurp;
    ;
    patty-->patty;
    ;
    values-->values;
    ;
    seqmath-->seqmath;
    ;
    csv2dbsrc-->csv2dbsrc;
    ;
    tam-->tam;
    ;
    gles-->gles;
    ;
    zfblast-->zfblast;
    ;
    barcode-->barcode;
    ;
    crc32-->crc32;
    ;
    remizstd-->remizstd;
    ;
    fastcgi-->fastcgi;
    ;
    nwnt-->nwnt;
    ;
    asyncdocker-->asyncdocker;
    ;
    nimrpc-->nimrpc;
    ;
    cittadino-->cittadino;
    ;
    rnim-->rnim;
    ;
    number_files-->number_files;
    ;
    nim_sdl2-->nim_sdl2;
    ;
    webdavclient-->webdavclient;
    ;
    resolv-->resolv;
    ;
    github-2vg-mofuhttputils-->github-2vg-mofuhttputils;
    ;
    pluginmanager-->pluginmanager;
    ;
    psutil-->psutil;
    ;
    sync-->sync;
    ;
    jnim-->jnim;
    ;
    spacenimtraders-->spacenimtraders;
    ;
    utf8tests-->utf8tests;
    ;
    expat-->expat;
    ;
    honeycomb-->honeycomb;
    ;
    ladder-->ladder;
    ;
    nimi3status-->nimi3status;
    ;
    hpprint-->hpprint;
    ;
    tinydialogs-->tinydialogs;
    ;
    hastyscribe-->hastyscribe;
    ;
    ptrace-->ptrace;
    ;
    terminaltables-->terminaltables;
    ;
    simpleast-->simpleast;
    ;
    nimscripter-->nimscripter;
    ;
    sayhissatsuwaza-->sayhissatsuwaza;
    ;
    rect_packer-->rect_packer;
    ;
    nimtactoe-->nimtactoe;
    ;
    porter-->porter;
    ;
    zxcvbn-->zxcvbn;
    ;
    eternity-->eternity;
    ;
    useragents-->useragents;
    ;
    mime-->mime;
    ;
    ngspice-->ngspice;
    ;
    github-disruptek-gittyup-->github-disruptek-gittyup;
    ;
    nhsl-->nhsl;
    ;
    romans-->romans;
    ;
    breeze-->breeze;
    ;
    retranslator-->retranslator;
    ;
    fsm-->fsm;
    ;
    webaudio-->webaudio;
    ;
    linalg-->linalg;
    ;
    oaitools-->oaitools;
    ;
    timecop-->timecop;
    ;
    composition-->composition;
    ;
    streamfix-->streamfix;
    ;
    tf2plug-->tf2plug;
    ;
    cirru_edn-->cirru_edn;
    ;
    subfield-->subfield;
    ;
    opus-->opus;
    ;
    wnim-->wnim;
    ;
    neoid-->neoid;
    ;
    monocypher-->monocypher;
    ;
    osdialog-->osdialog;
    ;
    tim_sort-->tim_sort;
    ;
    websocketx-->websocketx;
    ;
    fsmonitor-->fsmonitor;
    ;
    drawille-->drawille;
    ;
    emerald-->emerald;
    ;
    ad-->ad;
    ;
    jsmn-->jsmn;
    ;
    macroutils-->macroutils;
    ;
    nitro-->nitro;
    ;
    wavecore-->wavecore;
    ;
    aqcalc-->aqcalc;
    ;
    meow-->meow;
    ;
    twitter-->twitter;
    ;
    supranim-->supranim;
    ;
    phylogeni-->phylogeni;
    ;
    asyncthreadpool-->asyncthreadpool;
    ;
    conventional_semver-->conventional_semver;
    ;
    github-disruptek-badresults-->github-disruptek-badresults;
    ;
    nimdenter-->nimdenter;
    ;
    etf-->etf;
    ;
    suru-->suru;
    ;
    chronicles-->chronicles;
    ;
    bgfx-->bgfx;
    ;
    python3-->python3;
    ;
    nimrod-glfw-->nimrod-glfw;
    ;
    spacenav-->spacenav;
    ;
    luna-->luna;
    ;
    ajax-->ajax;
    ;
    impulse_engine-->impulse_engine;
    ;
    metrics-->metrics;
    ;
    pas2nim-->pas2nim;
    ;
    phosphor-->phosphor;
    ;
    gapbuffer-->gapbuffer;
    ;
    graphql-->graphql;
    ;
    gitapi-->gitapi;
    ;
    arksys-->arksys;
    ;
    fusion-->fusion;
    ;
    github-2vg-mofuparser-->github-2vg-mofuparser;
    ;
    isense-->isense;
    ;
    nimroutine-->nimroutine;
    ;
    random-->random;
    ;
    zippy-->zippy;
    ;
    gentabs-->gentabs;
    ;
    rlp-->rlp;
    ;
    jstin-->jstin;
    ;
    rpgsheet-->rpgsheet;
    ;
    termnovel-->termnovel;
    ;
    bytes2human-->bytes2human;
    ;
    stomp-->stomp;
    ;
    echon-->echon;
    ;
    finalseg-->finalseg;
    ;
    nimbpf-->nimbpf;
    ;
    pwned-->pwned;
    ;
    choosenimgui-->choosenimgui;
    ;
    lua-->lua;
    ;
    serialport-->serialport;
    ;
    desim-->desim;
    ;
    gimg-->gimg;
    ;
    ptr_math-->ptr_math;
    ;
    nimcuda-->nimcuda;
    ;
    x11-->x11;
    ;
    stint-->stint;
    ;
    filetype-->filetype;
    ;
    io-oculus-->io-oculus;
    ;
    unpack-->unpack;
    ;
    xmltools-->xmltools;
    ;
    glm-->glm;
    ;
    symbolicnim-->symbolicnim;
    ;
    pcgbasic-->pcgbasic;
    ;
    oauth-->oauth;
    ;
    chipmunk7_demos-->chipmunk7_demos;
    ;
    ttmath-->ttmath;
    ;
    zxcvbnim-->zxcvbnim;
    ;
    nicy-->nicy;
    ;
    openweathermap-->openweathermap;
    ;
    i18n-->i18n;
    ;
    mnemonic-->mnemonic;
    ;
    nasher-->nasher;
    ;
    diffoutput-->diffoutput;
    ;
    neverwinter-->neverwinter;
    ;
    tmplpro-->tmplpro;
    ;
    pipe-->pipe;
    ;
    ngxcmod-->ngxcmod;
    ;
    nimbus-->nimbus;
    ;
    geohash-->geohash;
    ;
    i3ipc-->i3ipc;
    ;
    limdb-->limdb;
    ;
    preserves-->preserves;
    ;
    simplepng-->simplepng;
    ;
    nimarrow-->nimarrow;
    ;
    prompt-->prompt;
    ;
    raytracingalgorithm-->raytracingalgorithm;
    ;
    plotly-->plotly;
    ;
    libmpdclient-->libmpdclient;
    ;
    nimpc-->nimpc;
    ;
    polybool-->polybool;
    ;
    pykot-->pykot;
    ;
    github-hamidb80-nimcoverage-->github-hamidb80-nimcoverage;
    ;
    cmd-->cmd;
    ;
    alsa-->alsa;
    ;
    grafanim-->grafanim;
    ;
    optional_t-->optional_t;
    ;
    mmgeoip-->mmgeoip;
    ;
    github-zedeus-redis-->github-zedeus-redis;
    ;
    ago-->ago;
    ;
    coalesce-->coalesce;
    ;
    easy_sqlite3-->easy_sqlite3;
    ;
    aossoa-->aossoa;
    ;
    nimja-->nimja;
    ;
    nimsl-->nimsl;
    ;
    mcmurry-->mcmurry;
    ;
    murmurhash-->murmurhash;
    ;
    nimviz-->nimviz;
    ;
    d3-->d3;
    ;
    github-pmunch-docopt-->github-pmunch-docopt;
    ;
    sha3-->sha3;
    ;
    leveldb-->leveldb;
    ;
    multicast-->multicast;
    ;
    collections-->collections;
    ;
    constants-->constants;
    ;
    gifenc-->gifenc;
    ;
    sam-->sam;
    ;
    strslice-->strslice;
    ;
    taskqueue-->taskqueue;
    ;
    github-nimgl-glfw-->github-nimgl-glfw;
    ;
    treesitter_python-->treesitter_python;
    ;
    xam-->xam;
    ;
    ustring-->ustring;
    ;
    rc4-->rc4;
    ;
    nimlangserver-->nimlangserver;
    ;
    redissessions-->redissessions;
    ;
    mc_events-->mc_events;
    ;
    asyncpg-->asyncpg;
    ;
    nimdata-->nimdata;
    ;
    amysql-->amysql;
    ;
    lscolors-->lscolors;
    ;
    marggers-->marggers;
    ;
    treesitter_c-->treesitter_c;
    ;
    usagov-->usagov;
    ;
    github-pmunch-x11-->github-pmunch-x11;
    ;
    wiringpinim-->wiringpinim;
    ;
    negamax-->negamax;
    ;
    maze-->maze;
    ;
    gpx-->gpx;
    ;
    checkpack-->checkpack;
    ;
    illwill-->illwill;
    ;
    argon2_bind-->argon2_bind;
    ;
    servy-->servy;
    ;
    nimsimd-->nimsimd;
    ;
    psutilim-->psutilim;
    ;
    owoifynim-->owoifynim;
    ;
    edens-->edens;
    ;
    servclip-->servclip;
    ;
    parsepage-->parsepage;
    ;
    geocoding-->geocoding;
    ;
    useradd-->useradd;
    ;
    github-yglukhov-bearssl_pkey_decoder-->github-yglukhov-bearssl_pkey_decoder;
    ;
    opengl-->opengl;
    ;
    sling-->sling;
    ;
    shiori_charset_convert-->shiori_charset_convert;
    ;
    unicode_numbers-->unicode_numbers;
    ;
    dav1d-->dav1d;
    ;
    autoderef-->autoderef;
    ;
    dnsclient-->dnsclient;
    ;
    murmur-->murmur;
    ;
    xmldomparser-->xmldomparser;
    ;
    iputils-->iputils;
    ;
    nimics-->nimics;
    ;
    entgrep-->entgrep;
    ;
    isocodes-->isocodes;
    ;
    treesitter_typescript-->treesitter_typescript;
    ;
    miniblink-->miniblink;
    ;
    cliche-->cliche;
    ;
    mqtt-->mqtt;
    ;
    threading-->threading;
    ;
    nint128-->nint128;
    ;
    npg-->npg;
    ;
    xml-->xml;
    ;
    nimfp-->nimfp;
    ;
    zfdbms-->zfdbms;
    ;
    db_nimternalsql-->db_nimternalsql;
    ;
    serializetools-->serializetools;
    ;
    json_rpc-->json_rpc;
    ;
    bamboo_websocket-->bamboo_websocket;
    ;
    ftd2xx-->ftd2xx;
    ;
    github-yglukhov-ttf-->github-yglukhov-ttf;
    ;
    owlkettle-->owlkettle;
    ;
    blscurve-->blscurve;
    ;
    webterminal-->webterminal;
    ;
    allographer-->allographer;
    ;
    compactdict-->compactdict;
    ;
    mealdb-->mealdb;
    ;
    jser-->jser;
    ;
    bio-->bio;
    ;
    uap-->uap;
    ;
    github-subsetpark-nim-stomp-->github-subsetpark-nim-stomp;
    ;
    minhash-->minhash;
    ;
    skinterpolate-->skinterpolate;
    ;
    sliceutils-->sliceutils;
    ;
    redisparser-->redisparser;
    ;
    base62-->base62;
    ;
    soundio-->soundio;
    ;
    argument_parser-->argument_parser;
    ;
    webp-->webp;
    ;
    xmlio-->xmlio;
    ;
    pylib-->pylib;
    ;
    sdl1-->sdl1;
    ;
    excelin-->excelin;
    ;
    hmisc-->hmisc;
    ;
    nimdotenv-->nimdotenv;
    ;
    elvis-->elvis;
    ;
    quickjs4nim-->quickjs4nim;
    ;
    proton-->proton;
    ;
    nimcrypt-->nimcrypt;
    ;
    c4-->c4;
    ;
    sorta-->sorta;
    ;
    css_html_minify-->css_html_minify;
    ;
    sctp-->sctp;
    ;
    loco-->loco;
    ;
    nmiline-->nmiline;
    ;
    whois-->whois;
    ;
    nimgame-->nimgame;
    ;
    dbus-->dbus;
    ;
    timestamp-->timestamp;
    ;
    unicodedb-->unicodedb;
    ;
    sums-->sums;
    ;
    nim_cexc-->nim_cexc;
    ;
    shmk-->shmk;
    ;
    lazy_rest-->lazy_rest;
    ;
    xcm-->xcm;
    ;
    neel-->neel;
    ;
    cmixer_sdl2-->cmixer_sdl2;
    ;
    easy_bcrypt-->easy_bcrypt;
    ;
    shared-->shared;
    ;
    slimdown-->slimdown;
    ;
    fidget-->fidget;
    ;
    latinize-->latinize;
    ;
    mdlldk-->mdlldk;
    ;
    tuples-->tuples;
    ;
    flatdb-->flatdb;
    ;
    nimp5-->nimp5;
    ;
    github-nim-works-cps-->github-nim-works-cps;
    ;
    nimcmaes-->nimcmaes;
    ;
    websocket-->websocket;
    ;
    samson-->samson;
    ;
    jsbind-->jsbind;
    ;
    dashing-->dashing;
    ;
    bluu-->bluu;
    ;
    discordnim-->discordnim;
    ;
    oculus-->oculus;
    ;
    nimdbx-->nimdbx;
    ;
    ethash-->ethash;
    ;
    rsvg-->rsvg;
    ;
    sodium-->sodium;
    ;
    opentdb-->opentdb;
    ;
    omnicollider-->omnicollider;
    ;
    bencode-->bencode;
    ;
    isa-->isa;
    ;
    libovr-->libovr;
    ;
    wzeegrid-->wzeegrid;
    ;
    remotery-->remotery;
    ;
    nimmonocypher-->nimmonocypher;
    ;
    classy-->classy;
    ;
    loki-->loki;
    ;
    translation-->translation;
    ;
    winim-->winim;
    ;
    paravim-->paravim;
    ;
    sunvox-->sunvox;
    ;
    bcrypt-->bcrypt;
    ;
    simpleot-->simpleot;
    ;
    cassette-->cassette;
    ;
    otp-->otp;
    ;
    cirru_parser-->cirru_parser;
    ;
    nimalpm-->nimalpm;
    ;
    urlshortener-->urlshortener;
    ;
    nim_curry-->nim_curry;
    ;
    nimrat-->nimrat;
    ;
    stb_truetype-->stb_truetype;
    ;
    chronos-->chronos;
    ;
    sndhdr-->sndhdr;
    ;
    github-liquid600pgm-nim-glm-->github-liquid600pgm-nim-glm;
    ;
    texttospeech-->texttospeech;
    ;
    npeg-->npeg;
    ;
    oop_utils-->oop_utils;
    ;
    harpoon-->harpoon;
    ;
    htsparse-->htsparse;
    ;
    confutils-->confutils;
    ;
    hyperscript-->hyperscript;
    ;
    norx-->norx;
    ;
    riff-->riff;
    ;
    hostname-->hostname;
    ;
    awss3-->awss3;
    ;
    cutelog-->cutelog;
    ;
    jack-->jack;
    ;
    secp256k1-->secp256k1;
    ;
    tm_client-->tm_client;
    ;
    nodem-->nodem;
    ;
    shorteststring-->shorteststring;
    ;
    encode-->encode;
    ;
    ast_pattern_matching-->ast_pattern_matching;
    ;
    libfuzzer-->libfuzzer;
    ;
    kashae-->kashae;
    ;
    github-yglukhov-wasmrt-->github-yglukhov-wasmrt;
    ;
    bionim-->bionim;
    ;
    nake-->nake;
    ;
    mt-->mt;
    ;
    markdown-->markdown;
    ;
    notmuch-->notmuch;
    ;
    ansitohtml-->ansitohtml;
    ;
    reframe-->reframe;
    ;
    deser-->deser;
    ;
    syllables-->syllables;
    ;
    fpn-->fpn;
    ;
    dropbox_filename_sanitizer-->dropbox_filename_sanitizer;
    ;
    nimclutter-->nimclutter;
    ;
    buffer-->buffer;
    ;
    eachdo-->eachdo;
    ;
    normalize-->normalize;
    ;
    noise-->noise;
    ;
    db_presto-->db_presto;
    ;
    numnim-->numnim;
    ;
    anybar-->anybar;
    ;
    genieos-->genieos;
    ;
    nim_cjson-->nim_cjson;
    ;
    python-->python;
    ;
    simplediff-->simplediff;
    ;
    slugify-->slugify;
    ;
    futhark-->futhark;
    ;
    sparkline-->sparkline;
    ;
    ogham-->ogham;
    ;
    libp2p-->libp2p;
    ;
    plists-->plists;
    ;
    treesitter_bash-->treesitter_bash;
    ;
    nimqml-->nimqml;
    ;
    sphincs-->sphincs;
    ;
    resultsutils-->resultsutils;
    ;
    dslutils-->dslutils;
    ;
    siwin-->siwin;
    ;
    systimes-->systimes;
    ;
    webview-->webview;
    ;
    chrono-->chrono;
    ;
    freetype-->freetype;
    ;
    treesitter_javascript-->treesitter_javascript;
    ;
    github-tormund-nester-->github-tormund-nester;
    ;
    wttrin-->wttrin;
    ;
    libnetfilter_queue-->libnetfilter_queue;
    ;
    irc-->irc;
    ;
    tencil-->tencil;
    ;
    treesitter_cpp-->treesitter_cpp;
    ;
    geoip-->geoip;
    ;
    httpbeast-->httpbeast;
    ;
    lapp-->lapp;
    ;
    nim7z-->nim7z;
    ;
    sprymicro-->sprymicro;
    ;
    geometryutils-->geometryutils;
    ;
    nwt-->nwt;
    ;
    sitmo-->sitmo;
    ;
    palette-->palette;
    ;
    toxcore-->toxcore;
    ;
    nimpass-->nimpass;
    ;
    emitter-->emitter;
    ;
    timelog-->timelog;
    ;
    einheit-->einheit;
    ;
    nsh-->nsh;
    ;
    svdpi-->svdpi;
    ;
    syphus-->syphus;
    ;
    nlopt-->nlopt;
    ;
    bitvector-->bitvector;
    ;
    tokarax-->tokarax;
    ;
    dogapi-->dogapi;
    ;
    nordnet-->nordnet;
    ;
    tome-->tome;
    ;
    fab-->fab;
    ;
    nesm-->nesm;
    ;
    snappy-->snappy;
    ;
    turn_based_game-->turn_based_game;
    ;
    vidhdr-->vidhdr;
    ;
    jsutils-->jsutils;
    ;
    localize-->localize;
    ;
    nimkov-->nimkov;
    ;
    random_font_color-->random_font_color;
    ;
    ed25519-->ed25519;
    ;
    fushin-->fushin;
    ;
    github-disruptek-assume-->github-disruptek-assume;
    ;
    stashtable-->stashtable;
    ;
    colorize-->colorize;
    ;
    p4ztag_to_json-->p4ztag_to_json;
    ;
    suber-->suber;
    ;
    ludens-->ludens;
    ;
    mustache-->mustache;
    ;
    github_api-->github_api;
    ;
    asciigraph-->asciigraph;
    ;
    ndb-->ndb;
    ;
    dnd-->dnd;
    ;
    nmark-->nmark;
    ;
    github-status-im-news-->github-status-im-news;
    ;
    github-disruptek-testes-->github-disruptek-testes;
    ;
    htmltovdom-->htmltovdom;
    ;
    nimcrypto-->nimcrypto;
    ;
    gsl-->gsl;
    ;
    sonic-->sonic;
    ;
    jsonschema-->jsonschema;
    ;
    denim_ui_cairo-->denim_ui_cairo;
    ;
    adb-->adb;
    ;
    keystone-->keystone;
    ;
    protobuf-->protobuf;
    ;
    opensimplexnoise-->opensimplexnoise;
    ;
    nimhdf5-->nimhdf5;
    ;
    playground-->playground;
    ;
    svgo-->svgo;
    ;
    locale-->locale;
    ;
    biscuits-->biscuits;
    ;
    arraymancer-->arraymancer;
    ;
    kview-->kview;
    ;
    list_comprehension-->list_comprehension;
    ;
    rodcli-->rodcli;
    ;
    zip-->zip;
    ;
    z3nim-->z3nim;
    ;
    torim-->torim;
    ;
    layonara_nwn-->layonara_nwn;
    ;
    nimbass-->nimbass;
    ;
    testutils-->testutils;
    ;
    zfcore-->zfcore;
    ;
    ternary_tree-->ternary_tree;
    ;
    witai-->witai;
    ;
    pine-->pine;
    ;
    autotyper-->autotyper;
    ;
    canonicaljson-->canonicaljson;
    ;
    nregex-->nregex;
    ;
    nimsnappyc-->nimsnappyc;
    ;
    wchart-->wchart;
    ;
    criterion-->criterion;
    ;
    httputils-->httputils;
    ;
    lastfm-->lastfm;
    ;
    jalali_nim-->jalali_nim;
    ;
    mentat-->mentat;
    ;
    nimp-->nimp;
    ;
    sphinx-->sphinx;
    ;
    io-gles-->io-gles;
    ;
    sharedmempool-->sharedmempool;
    ;
    pych-->pych;
    ;
    randpw-->randpw;
    ;
    hypixel-->hypixel;
    ;
    antlr4nim-->antlr4nim;
    ;
    riimut-->riimut;
    ;
    tim-->tim;
    ;
    libsodium-->libsodium;
    ;
    minecraft_server_status-->minecraft_server_status;
    ;
    monerorpc-->monerorpc;
    ;
    textformats-->textformats;
    ;
    anycase-->anycase;
    ;
    devil-->devil;
    ;
    tcl-->tcl;
    ;
    kmod-->kmod;
    ;
    nimga-->nimga;
    ;
    ssz_serialization-->ssz_serialization;
    ;
    loopfusion-->loopfusion;
    ;
    uuid-->uuid;
    ;
    blake2-->blake2;
    ;
    packets-->packets;
    ;
    eastasianwidth-->eastasianwidth;
    ;
    xxtea-->xxtea;
    ;
    cocktaildb-->cocktaildb;
    ;
    react-->react;
    ;
    wings-->wings;
    ;
    binaryheap-->binaryheap;
    ;
    ws-->ws;
    ;
    magic-->magic;
    ;
    nuuid-->nuuid;
    ;
    networkutils-->networkutils;
    ;
    meta-->meta;
    ;
    mpwc-->mpwc;
    ;
    libevdev-->libevdev;
    ;
    xxhash-->xxhash;
    ;
    nimterop-->nimterop;
    ;
    gnu-->gnu;
    ;
    tiny_sqlite-->tiny_sqlite;
    ;
    taglib-->taglib;
    ;
    pkginfo-->pkginfo;
    ;
    colorsys-->colorsys;
    ;
    pwnedpass-->pwnedpass;
    ;
    mpeg-->mpeg;
    ;
    notetxt-->notetxt;
    ;
    jesterjson-->jesterjson;
    ;
    nimbitarray-->nimbitarray;
    ;
    simpleflake-->simpleflake;
    ;
    audiodb-->audiodb;
    ;
    seriesdetiempoar-->seriesdetiempoar;
    ;
    openapi-->openapi;
    ;
    aporia-->aporia;
    ;
    denim_ui-->denim_ui;
    ;
    github-zacharycarter-nuklear-->github-zacharycarter-nuklear;
    ;
    objc_runtime-->objc_runtime;
    ;
    github-disruptek-balls-->github-disruptek-balls;
    ;
    origin-->origin;
    ;
    smnar-->smnar;
    ;
    euclidean-->euclidean;
    ;
    steam-->steam;
    ;
    awesome_rmdir-->awesome_rmdir;
    ;
    nimassets-->nimassets;
    ;
    pythonize-->pythonize;
    ;
    pg_util-->pg_util;
    ;
    algebra-->algebra;
    ;
    geminim-->geminim;
    ;
    netty-->netty;
    ;
    overpass-->overpass;
    ;
    github-iffy-asynctools-->github-iffy-asynctools;
    ;
    telebot-->telebot;
    ;
    arrayfirenim-->arrayfirenim;
    ;
    nimboost-->nimboost;
    ;
    beanstalkd-->beanstalkd;
    ;
    compiler-->compiler;
    ;
    nrpl-->nrpl;
    ;
    nptr-->nptr;
    ;
    millie-->millie;
    ;
    nimbigwig-->nimbigwig;
    ;
    upraises-->upraises;
    ;
    staticglfw-->staticglfw;
    ;
    once-->once;
    ;
    gamelight-->gamelight;
    ;
    nigui-->nigui;
    ;
    xplm-nim-->xplm-nim;
    ;
    finder-->finder;
    ;
    jupyternim-->jupyternim;
    ;
    github-jyapayne-nim-glfw-->github-jyapayne-nim-glfw;
    ;
    zstd-->zstd;
    ;
    xlsx-->xlsx;
    ;
    frag-->frag;
    ;
    protocoled-->protocoled;
    ;
    onedrive-->onedrive;
    ;
    nre-->nre;
    ;
    sqlbuilder-->sqlbuilder;
    ;
    nimrtlsdr-->nimrtlsdr;
    ;
    array2d-->array2d;
    ;
    dual-->dual;
    ;
    freegeoip-->freegeoip;
    ;
    simpledecimal-->simpledecimal;
    ;
    tecs-->tecs;
    ;
    scorper-->scorper;
    ;
    coverage-->coverage;
    ;
    latexdsl-->latexdsl;
    ;
    sound-->sound;
    ;
    parsetoml-->parsetoml;
    ;
    dik-->dik;
    ;
    imlib2-->imlib2;
    ;
    ormin-->ormin;
    ;
    randgen-->randgen;
    ;
    midnight_dynamite-->midnight_dynamite;
    ;
    nodesnim-->nodesnim;
    ;
    skbintext-->skbintext;
    ;
    subhook-->subhook;
    ;
    uri2-->uri2;
    ;
    semver-->semver;
    ;
    lolcat-->lolcat;
    ;
    adix-->adix;
    ;
    pager-->pager;
    ;
    nim-libgd-->nim-libgd;
    ;
    pythonpathlib-->pythonpathlib;
    ;
    sdl2_nim-->sdl2_nim;
    ;
    config-->config;
    ;
    io-usb-->io-usb;
    ;
    vla-->vla;
    ;
    datetime_parse-->datetime_parse;
    ;
    nimzend-->nimzend;
    ;
    constructor-->constructor;
    ;
    fftw3-->fftw3;
    ;
    ranges-->ranges;
    ;
    getmac-->getmac;
    ;
    github-->github;
    ;
    robotparser-->robotparser;
    ;
    nimquery-->nimquery;
    ;
    aws_sdk-->aws_sdk;
    ;
    tsundoku-->tsundoku;
    ;
    wyhash-->wyhash;
    ;
    pari-->pari;
    ;
    dbschema-->dbschema;
    ;
    icon-->icon;
    ;
    qwertycd-->qwertycd;
    ;
    redneck_translator-->redneck_translator;
    ;
    serial-->serial;
    ;
    sos-->sos;
    ;
    shorturl-->shorturl;
    ;
    cpuwhat-->cpuwhat;
    ;
    qrcode-->qrcode;
    ;
    clblast-->clblast;
    ;
    leopard-->leopard;
    ;
    currying-->currying;
    ;
    nofi-->nofi;
    ;
    opencv-->opencv;
    ;
    norm-->norm;
    ;
    libharu-->libharu;
    ;
    osureplay-->osureplay;
    ;
    plz-->plz;
    ;
    illwill_unsafe-->illwill_unsafe;
    ;
    drng-->drng;
    ;
    nimcdl-->nimcdl;
    ;
    ulid-->ulid;
    ;
    mouse-->mouse;
    ;
    cal-->cal;
    ;
    neo-->neo;
    ;
    fmod-->fmod;
    ;
    with-->with;
    ;
    github-planety-cookies-->github-planety-cookies;
    ;
    nimpdf-->nimpdf;
    ;
    github-enthus1ast-nimcommandparser-->github-enthus1ast-nimcommandparser;
    ;
    httpauth-->httpauth;
    ;
    shell-->shell;
    ;
    nshout-->nshout;
    ;
    print-->print;
    ;
    flippy-->flippy;
    ;
    jsony-->jsony;
    ;
    ptest-->ptest;
    ;
    spwd-->spwd;
    ;
    nimcat-->nimcat;
    ;
    nimsnappy-->nimsnappy;
    ;
    kslog-->kslog;
    ;
    boneio-->boneio;
    ;
    assimp-->assimp;
    ;
    schedules-->schedules;
    ;
    htmlunescape-->htmlunescape;
    ;
    masterpassword-->masterpassword;
    ;
    wepoll-->wepoll;
    ;
    recaptcha-->recaptcha;
    ;
    faststreams-->faststreams;
    ;
    sumtypes-->sumtypes;
    ;
    blarg-->blarg;
    ;
    nimtraits-->nimtraits;
    ;
    hottie-->hottie;
    ;
    taskman-->taskman;
    ;
    nage-->nage;
    ;
    nimplehttpserver-->nimplehttpserver;
    ;
    units-->units;
    ;
    coverartarchive-->coverartarchive;
    ;
    strfmt-->strfmt;
    ;
    sweetanitify-->sweetanitify;
    ;
    nexus-->nexus;
    ;
    ncurses-->ncurses;
    ;
    flickr_image_bot-->flickr_image_bot;
    ;
    badgemaker-->badgemaker;
    ;
    clr-->clr;
    ;
    frida-->frida;
    ;
    dpdk-->dpdk;
    ;
    ducominer-->ducominer;
    ;
    nimx-->nimx;
    ;
    std_shims-->std_shims;
    ;
    unimcli-->unimcli;
    ;
    websock-->websock;
    ;
    mcresponse-->mcresponse;
    ;
    battery_widget-->battery_widget;
    ;
    itchio-->itchio;
    ;
    nimbler-->nimbler;
    ;
    github_release-->github_release;
    ;
    nico-->nico;
    ;
    golden-->golden;
    ;
    falas-->falas;
    ;
    gamelib-->gamelib;
    ;
    dnsprotec-->dnsprotec;
    ;
    strenc-->strenc;
    ;
    hparse-->hparse;
    ;
    variant-->variant;
    ;
    nimble-->nimble;
    ;
    templates-->templates;
    ;
    iup-->iup;
    ;
    run_exe-->run_exe;
    ;
    libsvm_legacy-->libsvm_legacy;
    ;
    glossolalia-->glossolalia;
    ;
    argparse-->argparse;
    ;
    niledb-->niledb;
    ;
    termstyle-->termstyle;
    ;
    urlly-->urlly;
    ;
    nimcb-->nimcb;
    ;
    typelists-->typelists;
    ;
    chipmunk7-->chipmunk7;
    ;
    nauthy-->nauthy;
    ;
    signals-->signals;
    ;
    native_dialogs-->native_dialogs;
    ;
    colorcol-->colorcol;
    ;
    zfplugs-->zfplugs;
    ;
    pnm-->pnm;
    ;
    stew-->stew;
    ;
    mpfit-->mpfit;
    ;
    matext-->matext;
    ;
    json_builder-->json_builder;
    ;
    nimler-->nimler;
    ;
    newfix-->newfix;
    ;
    treesitter_haskell-->treesitter_haskell;
    ;
    treesitter_ruby-->treesitter_ruby;
    ;
    nat_traversal-->nat_traversal;
    ;
    yukiko-->yukiko;
    ;
    nobject-->nobject;
    ;
    splitmix64-->splitmix64;
    ;
    science-->science;
    ;
    tinypool-->tinypool;
    ;
    c_alikes-->c_alikes;
    ;
    ffmpeg-->ffmpeg;
    ;
    discord_rpc-->discord_rpc;
    ;
    pg-->pg;
    ;
    windy-->windy;
    ;
    lmdb-->lmdb;
    ;
    awslambda-->awslambda;
    ;
    nimspice-->nimspice;
    ;
    orient-->orient;
    ;
    hashids-->hashids;
    ;
    bisect-->bisect;
    ;
    mongrel2-->mongrel2;
    ;
    toml_serialization-->toml_serialization;
    ;
    metar-->metar;
    ;
    socks-->socks;
    ;
    github-status-im-nim-taskpools-->github-status-im-nim-taskpools;
    ;
    nimrdkafka-->nimrdkafka;
    ;
    gcplat-->gcplat;
    ;
    nim_midi-->nim_midi;
    ;
    pcap-->pcap;
    ;
    winres-->winres;
    ;
    nimodpi-->nimodpi;
    ;
    nimage-->nimage;
    ;
    backoff-->backoff;
    ;
    iridium-->iridium;
    ;
    sigv4-->sigv4;
    ;
    wox-->wox;
    ;
    tnetstring-->tnetstring;
    ;
    odbcn-->odbcn;
    ;
    nimtrs-->nimtrs;
    ;
    polymorph-->polymorph;
    ;
    github-vindaar-seqmath-->github-vindaar-seqmath;
    ;
    arbitrary-->arbitrary;
    ;
    base32-->base32;
    ;
    open_elevation-->open_elevation;
    ;
    treesitter_ocaml-->treesitter_ocaml;
    ;
    rainbow-->rainbow;
    ;
    csvtable-->csvtable;
    ;
    ris-->ris;
    ;
    murmur3-->murmur3;
    ;
    nimpng-->nimpng;
    ;
    extmath-->extmath;
    ;
    rss-->rss;
    ;
    kaitai_struct_nim_runtime-->kaitai_struct_nim_runtime;
    ;
    iterutils-->iterutils;
    ;
    sequoia-->sequoia;
    ;
    fnmatch-->fnmatch;
    ;
    slappy-->slappy;
    ;
    cmixer-->cmixer;
    ;
    libarchibi-->libarchibi;
    ;
    fwrite-->fwrite;
    ;
    gtkgenui-->gtkgenui;
    ;
    formulas-->formulas;
    ;
    kiwi-->kiwi;
    ;
    wave-->wave;
    ;
    bn-->bn;
    ;
    uibuilder-->uibuilder;
    ;
    forestdb-->forestdb;
    ;
    nimmm-->nimmm;
    ;
    artemis-->artemis;
    ;
    notifishower-->notifishower;
    ;
    parasound-->parasound;
    ;
    statsd_client-->statsd_client;
    ;
    nimzbar-->nimzbar;
    ;
    timerpool-->timerpool;
    ;
    timezones-->timezones;
    ;
    github-disruptek-cps-->github-disruptek-cps;
    ;
    hotdoc-->hotdoc;
    ;
    boxy-->boxy;
    ;
    cdecl-->cdecl;
    ;
    expander-->expander;
    ;
    keyring-->keyring;
    ;
    noaa-->noaa;
    ;
    lapper-->lapper;
    ;
    puppy-->puppy;
    ;
    edlib-->edlib;
    ;
    github-enthus1ast-isprivateip-->github-enthus1ast-isprivateip;
    ;
    db-->db;
    ;
    jscanvas-->jscanvas;
    ;
    eminim-->eminim;
    ;
    geonames-->geonames;
    ;
    slicerator-->slicerator;
    ;
    limiter-->limiter;
    ;
    bio_seq-->bio_seq;
    ;
    shiori-->shiori;
    ;
    downit-->downit;
    ;
    nimna-->nimna;
    ;
    nimline-->nimline;
    ;
    nimbleimgui-->nimbleimgui;
    ;
    decisiontree-->decisiontree;
    ;
    bignum-->bignum;
    ;
    rconv-->rconv;
    ;
    bson-->bson;
    ;
    denim_ui_canvas-->denim_ui_canvas;
    ;
    validator-->validator;
    ;
    conio-->conio;
    ;
    vmath-->vmath;
    ;
    openstreetmap-->openstreetmap;
    ;
    redux-->redux;
    ;
    webdriver-->webdriver;
    ;
    lazy-->lazy;
    ;
    hexclock-->hexclock;
    ;
    niml-->niml;
    ;
    xcb-->xcb;
    ;
    hasts-->hasts;
    ;
    inim-->inim;
    ;
    news-->news;
    ;
    blurhash-->blurhash;
    ;
    minmaxheap-->minmaxheap;
    ;
    govee-->govee;
    ;
    dialogs-->dialogs;
    ;
    ikeahomesmart-->ikeahomesmart;
    ;
    asyncevents-->asyncevents;
    ;
    colorizeecho-->colorizeecho;
    ;
    eth-->eth;
    ;
    spacy-->spacy;
    ;
    astdot-->astdot;
    ;
    torm-->torm;
    ;
    oolib-->oolib;
    ;
    xmldom-->xmldom;
    ;
    naw-->naw;
    ;
    redismodules-->redismodules;
    ;
    jeknil-->jeknil;
    ;
    nimfinlib-->nimfinlib;
    ;
    epub-->epub;
    ;
    webgl-->webgl;
    ;
    lc-->lc;
    ;
    mddoc-->mddoc;
    ;
    github-pmunch-libclang-->github-pmunch-libclang;
    ;
    steganography-->steganography;
    ;
    clang-->clang;
    ;
    sol-->sol;
    ;
    suffer-->suffer;
    ;
    classes-->classes;
    ;
    github-zacharycarter-bgfxdotnim-->github-zacharycarter-bgfxdotnim;
    ;
    chonker-->chonker;
    ;
    libu2f-->libu2f;
    ;
    github-solitudesf-x11-->github-solitudesf-x11;
    ;
    gmp-->gmp;
    ;
    nimcoon-->nimcoon;
    ;
    db_wrapper-->db_wrapper;
    ;
    rodster-->rodster;
    ;
    skyhash-->skyhash;
    ;
    cmark-->cmark;
    ;
    libp2pdht-->libp2pdht;
    ;
    sfml-->sfml;
    ;
    spinner-->spinner;
    ;
    ansiutils-->ansiutils;
    ;
    ctrulib-->ctrulib;
    ;
    glew-->glew;
    ;
    libuv-->libuv;
    ;
    owo-->owo;
    ;
    ssh2-->ssh2;
    ;
    bigints-->bigints;
    ;
    polymers-->polymers;
    ;
    bearssl-->bearssl;
    ;
    scnim-->scnim;
    ;
    treesitter_rust-->treesitter_rust;
    ;
    myo-->myo;
    ;
    clapfn-->clapfn;
    ;
    xpm-->xpm;
    ;
    coinbase_pro-->coinbase_pro;
    ;
    timespec_get-->timespec_get;
    ;
    libipset-->libipset;
    ;
    gatabase-->gatabase;
    ;
    libgcrypt-->libgcrypt;
    ;
    notifications-->notifications;
    ;
    nesper-->nesper;
    ;
    kdialog-->kdialog;
    ;
    kdb-->kdb;
    ;
    kombinator-->kombinator;
    ;
    redisclient-->redisclient;
    ;
    swayipc-->swayipc;
    ;
    nicoru-->nicoru;
    ;
    chipmunk6-->chipmunk6;
    ;
    nimnoise-->nimnoise;
    ;
    nancy-->nancy;
    ;
    cucumber-->cucumber;
    ;
    jswebsockets-->jswebsockets;
    ;
    github-solitudesf-nim-dbus-->github-solitudesf-nim-dbus;
    ;
    py2nim-->py2nim;
    ;
    delaunay-->delaunay;
    ;
    png-->png;
    ;
    rabbit-->rabbit;
    ;
    rbtree-->rbtree;
    ;
    simple_graph-->simple_graph;
    ;
    libffi-->libffi;
    ;
    taskpools-->taskpools;
    ;
    libsha-->libsha;
    ;
    q-->q;
    ;
    protobuf_serialization-->protobuf_serialization;
    ;
    periapsisengine-->periapsisengine;
    ;
    deser_json-->deser_json;
    ;
    libssh-->libssh;
    ;
    hastysite-->hastysite;
    ;
    dali-->dali;
    ;
    variantsugar-->variantsugar;
    ;
    pythonmath-->pythonmath;
    ;
    tnim-->tnim;
    ;
    chain-->chain;
    ;
    omnilog-->omnilog;
    ;
    polypbren-->polypbren;
    ;
    til-->til;
    ;
    guildenstern-->guildenstern;
    ;
    godot-->godot;
    ;
    ratel-->ratel;
    ;
    special_functions-->special_functions;
    ;
    nimaterial-->nimaterial;
    ;
    soundex-->soundex;
    ;
    triplets-->triplets;
    ;
    parseini-->parseini;
    ;
    nimlapack-->nimlapack;
    ;
    hmac-->hmac;
    ;
    srv-->srv;
    ;
    fltk-->fltk;
    ;
    nim_miniz-->nim_miniz;
    ;
    bluesoftcosmos-->bluesoftcosmos;
    ;
    listsv-->listsv;
    ;
    tcping-->tcping;
    ;
    opusenc-->opusenc;
    ;
    rena-->rena;
    ;
    ginger-->ginger;
    ;
    astronimy-->astronimy;
    ;
    huffman-->huffman;
    ;
    nimgen-->nimgen;
    ;
    yaml-->yaml;
    ;
    syslog-->syslog;
    ;
    nimblas-->nimblas;
    ;
    sysinfo-->sysinfo;
    ;
    pdcurses-->pdcurses;
    ;
    nimbioseq-->nimbioseq;
    ;
    nimhttpd-->nimhttpd;
    ;
    github-disruptek-rest-->github-disruptek-rest;
    ;
    paramidi-->paramidi;
    ;
    treesitter_java-->treesitter_java;
    ;
    nimqbittorrent-->nimqbittorrent;
    ;
    eventemitter-->eventemitter;
    ;
    nim_tiled-->nim_tiled;
    ;
    calendar-->calendar;
    ;
    pomtimer-->pomtimer;
    ;
    lockfreequeues-->lockfreequeues;
    ;
    memo-->memo;
    ;
    darwin-->darwin;
    ;
    blackvas_cli-->blackvas_cli;
    ;
    docopt-->docopt;
    ;
    libbacktrace-->libbacktrace;
    ;
    spdx_licenses-->spdx_licenses;
    ;
    webgui-->webgui;
    ;
    xdo-->xdo;
    ;
    presto-->presto;
    ;
    daemonim-->daemonim;
    ;
    paranim-->paranim;
    ;
    nimpb_protoc-->nimpb_protoc;
    ;
    pantry-->pantry;
    ;
    wpspin-->wpspin;
    ;
    gerbil-->gerbil;
    ;
    timeit-->timeit;
    ;
    argon2-->argon2;
    ;
    nimrcon-->nimrcon;
    ;
    sqlite3_abi-->sqlite3_abi;
    ;
    crap-->crap;
    ;
    catnip-->catnip;
    ;
    gifwriter-->gifwriter;
    ;
    github-timotheecour-asynctools-->github-timotheecour-asynctools;
    ;
    dimscmd-->dimscmd;
    ;
    alut-->alut;
    ;
    cassandra-->cassandra;
    ;
    itertools-->itertools;
    ;
    libgraph-->libgraph;
    ;
    alasgar-->alasgar;
    ;
    nimbmp-->nimbmp;
    ;
    ballena_itcher-->ballena_itcher;
    ;
    github-haxscramper-hlibssh2-->github-haxscramper-hlibssh2;
    ;
    treesitter-->treesitter;
    ;
    vmvc-->vmvc;
    ;
    intervalsets-->intervalsets;
    ;
    monit-->monit;
    ;
    primme-->primme;
    ;
    capnp-->capnp;
    ;
    eth_common-->eth_common;
    ;
    prettyvec-->prettyvec;
    ;
    static_server-->static_server;
    ;
    usigar-->usigar;
    ;
    nimpy-->nimpy;
    ;
    eris-->eris;
    ;
    asciitype-->asciitype;
    ;
    github-tandy-1000-uniony-->github-tandy-1000-uniony;
    ;
    msgpack-->msgpack;
    ;
    rtree-->rtree;
    ;
    slap-->slap;
    ;
    nimsuite-->nimsuite;
    ;
    argon2_highlevel-->argon2_highlevel;
    ;
    eth_keyfile-->eth_keyfile;
    ;
    gintro-->gintro;
    ;
    nimfmt-->nimfmt;
    ;
    printdebug-->printdebug;
    ;
    hangover-->hangover;
    ;
    accuratesums-->accuratesums;
    ;
    illwave-->illwave;
    ;
    lq-->lq;
    ;
    z3-->z3;
    ;
    notification-->notification;
    ;
    nimib-->nimib;
    ;
    sophia-->sophia;
    ;
    pop3-->pop3;
    ;
    nimbomb-->nimbomb;
    ;
    ffbookmarks-->ffbookmarks;
    ;
    treesitter_scala-->treesitter_scala;
    ;
    github-disruptek-ups-->github-disruptek-ups;
    ;
    nanomsg-->nanomsg;
    ;
    bitty-->bitty;
    ;
    plugins-->plugins;
    ;
    algebraicdatas-->algebraicdatas;
    ;
    nimgraphql-->nimgraphql;
    ;
    subnet-->subnet;
    ;
    treesitter_agda-->treesitter_agda;
    ;
    nimetry-->nimetry;
    ;
    cascade-->cascade;
    ;
    astar-->astar;
    ;
    maybe-->maybe;
    ;
    crowncalc-->crowncalc;
    ;
    flower-->flower;
    ;
    httpx-->httpx;
    ;
    ffpass-->ffpass;
    ;
    tagger-->tagger;
    ;
    vecmath-->vecmath;
    ;
    aur-->aur;
    ;
    interfaced-->interfaced;
    ;
    exporttosqlite3-->exporttosqlite3;
    ;
    morepretty-->morepretty;
    ;
    commandant-->commandant;
    ;
    complex-->complex;
    ;
    csvtools-->csvtools;
    ;
    nimfuzz-->nimfuzz;
    ;
    dtoa-->dtoa;
    ;
    github-dom96-zippy-->github-dom96-zippy;
    ;
    cliptomania-->cliptomania;
    ;
    bipbuffer-->bipbuffer;
    ;
    word2vec-->word2vec;
    ;
    github-gabbhack-anycase_fork-->github-gabbhack-anycase_fork;
    ;
    lda-->lda;
    ;
    unicodeplus-->unicodeplus;
    ;
    finals-->finals;
    ;
    pixie-->pixie;
    ;
    mongo-->mongo;
    ;
    genoiser-->genoiser;
    ;
    fletcher-->fletcher;
    ;
    horde3d-->horde3d;
    ;
    ipsumgenera-->ipsumgenera;
    ;
    nimlist-->nimlist;
    ;
    reactor-->reactor;
    ;
    flatty-->flatty;
    ;
    holst-->holst;
    ;
    packedargs-->packedargs;
    ;
    osinfo-->osinfo;
    ;
    options-->options;
    ;
    binio-->binio;
    ;
    pvim-->pvim;
    ;
    delight-->delight;
    ;
    perlin-->perlin;
    ;
    nimtesseract-->nimtesseract;
    ;
    requirementstxt-->requirementstxt;
    ;
    winimx-->winimx;
    ;
    cache-->cache;
    ;
    db_clickhouse-->db_clickhouse;
    ;
    deepspeech-->deepspeech;
    ;
    xiaomi-->xiaomi;
    ;
    pokereval-->pokereval;
    ;
    nimem-->nimem;
    ;
    qr-->qr;
    ;
    libravatar-->libravatar;
    ;
    netpbm-->netpbm;
    ;
    physfs-->physfs;
    ;
    basic3d-->basic3d;
    ;
    intel_hex-->intel_hex;
    ;
    persvector-->persvector;
    ;
    etcd_client-->etcd_client;
    ;
    nimates-->nimates;
    ;
    benchy-->benchy;
    ;
    stdext-->stdext;
    ;
    cmake-->cmake;
    ;
    fsnotify-->fsnotify;
    ;
    tor-->tor;
    ;
    sermon-->sermon;
    ;
    synthesis-->synthesis;
    ;
    wxpay-->wxpay;
    ;
    csvql-->csvql;
    ;
    alea-->alea;
    ;
    matplotnim-->matplotnim;
    ;
    hcparse-->hcparse;
    ;
    fowltek-->fowltek;
    ;
    dye-->dye;
    ;
    hldiff-->hldiff;
    ;
    grp-->grp;
    ;
    sksbox-->sksbox;
    ;
    unrolled-->unrolled;
    ;
    psy-->psy;
    ;
    about-->about;
    ;
    zlib-->zlib;
    ;
    fuse-->fuse;
    ;
    odsreader-->odsreader;
    ;
    metric-->metric;
    ;
    nwsync-->nwsync;
    ;
    imageman-->imageman;
    ;
    cirru_writer-->cirru_writer;
    ;
    asciitables-->asciitables;
    ;
    microparsec-->microparsec;
    ;
    vaultclient-->vaultclient;
    ;
    nap-->nap;
    ;
    unit-->unit;
    ;
    nimibook-->nimibook;
    ;
    packedjson-->packedjson;
    ;
    rangequeries-->rangequeries;
    ;
    binarylang-->binarylang;
    ;
    ms-->ms;
    ;
    oshostname-->oshostname;
    ;
    validateip-->validateip;
    ;
    parsesql-->parsesql;
    ;
    interface_implements-->interface_implements;
    ;
    pledge-->pledge;
    ;
    winregistry-->winregistry;
    ;
    keccak_tiny-->keccak_tiny;
    ;
    manu-->manu;
    ;
    uuid4-->uuid4;
    ;
    influx-->influx;
    ;
    nimgui-->nimgui;
    ;
    quickcrypt-->quickcrypt;
    ;
    htmlanticopy-->htmlanticopy;
    ;
    paramidib-->paramidib;
    ;
    basedon-->basedon;
    ;
    envconfig-->envconfig;
    ;
    bumpy-->bumpy;
    ;
    nimarrow_glib-->nimarrow_glib;
    ;
    mapbits-->mapbits;
    ;
    bitvec-->bitvec;
    ;
    reactorfuse-->reactorfuse;
    ;
    scram-->scram;
    ;
    sampletodolist-->sampletodolist;
    ;
    simdx86-->simdx86;
    ;
    treesitter_html-->treesitter_html;
    ;
    nest-->nest;
    ;
    paratext-->paratext;
    ;
    cowstrings-->cowstrings;
    ;
    glbits-->glbits;
    ;
    eth_p2p-->eth_p2p;
    ;
    parselicense-->parselicense;
    ;
    syndicate-->syndicate;
    ;
    digitalocean-->digitalocean;
    ;
    base64_decoder-->base64_decoder;
    ;
    nimlsp-->nimlsp;
    ;
    nimaes-->nimaes;
    ;
    graphics-->graphics;
    ;
    nimmikudance-->nimmikudance;
    ;
    nimhq-->nimhq;
    ;
    parsegemini-->parsegemini;
    ;
    pl0t-->pl0t;
    ;
    github-yglukhov-async_http_request-->github-yglukhov-async_http_request;
    ;
    github-hugogranstrom-cdt-->github-hugogranstrom-cdt;
    ;
    cppstl-->cppstl;
    ;
    nimatic-->nimatic;
    ;
    node-->node;
    ;
    nimkalc-->nimkalc;
    ;
    directnimrod-->directnimrod;
    ;
    testrunner-->testrunner;
    ;
    nimbox-->nimbox;
    ;
    chroma-->chroma;
    ;
    naylib-->naylib;
    ;
    pgxcrown-->pgxcrown;
    ;
    tempfile-->tempfile;
    ;
    httpstat-->httpstat;
    ;
    ntangle-->ntangle;
    ;
    typography-->typography;
    ;
    wauto-->wauto;
    ;
    github-disruptek-semaphores-->github-disruptek-semaphores;
    ;
    sass-->sass;
    ;
    io-spacenav-->io-spacenav;
    ;
    unittest2-->unittest2;
    ;
    bpg-->bpg;
    ;
    nimsocks-->nimsocks;
    ;
    moduleinit-->moduleinit;
    ;
    gnuplot-->gnuplot;
    ;
    rosencrantz-->rosencrantz;
    ;
    therapist-->therapist;
    ;
    bingo-->bingo;
    ;
    ringbuffer-->ringbuffer;
    ;
    skeasing-->skeasing;
    ;
    imstyle-->imstyle;
    ;
    libnx-->libnx;
    ;
    nimmarc-->nimmarc;
    ;
    luhncheck-->luhncheck;
    ;
    sequester-->sequester;
    ;
    scraper-->scraper;
    ;
    remarker_light-->remarker_light;
    ;
    sue-->sue;
    ;
    vecio-->vecio;
    ;
    appdirs-->appdirs;
    ;
    nimblegui-->nimblegui;
    ;
    mcd-->mcd;
    ;
    asyncredis-->asyncredis;
    ;
    bloom-->bloom;
    ;
    htmlgenerator-->htmlgenerator;
    ;
    lrucache-->lrucache;
    ;
    nery-->nery;
    ;
    configparser-->configparser;
    ;
    svvpi-->svvpi;
    ;
    sysrandom-->sysrandom;
    ;
    hdrawing-->hdrawing;
    ;
    scgi-->scgi;
    ;
    weightedgraph-->weightedgraph;
    ;
    nimtomd-->nimtomd;
    ;
    akane-->akane;
    ;
    saya-->saya;
    ;
    nimwave-->nimwave;
    ;
    nimobserver-->nimobserver;
    ;
    feta-->feta;
    ;
    suggest-->suggest;
    ;
    io-isense-->io-isense;
    ;
    quadtree-->quadtree;
    ;
    couchdb-->couchdb;
    ;
    kinto-->kinto;
    ;
    nimtetris-->nimtetris;
    ;
    sparseset-->sparseset;
    ;
    pfring-->pfring;
    ;
    daemon-->daemon;
    ;
    github-dadadani-nim-random-->github-dadadani-nim-random;
    ;
    fision-->fision;
    ;
    json2xml-->json2xml;
    ;
    cello-->cello;
    ;
    slim-->slim;
    ;
    funchook-->funchook;
    ;
    dumpincludes-->dumpincludes;
    ;
    github-planety-cookiejar-->github-planety-cookiejar;
    ;
    hottext-->hottext;
    ;
    spdk-->spdk;
    ;
    uspokoysa-->uspokoysa;
    ;
    w8crc-->w8crc;
    ;
    nimsvg-->nimsvg;
    ;
    tinamou-->tinamou;
    ;
    osrm-->osrm;
    ;
    libvlc-->libvlc;
    ;
    nodejs-->nodejs;
    ;
    tiger-->tiger;
    ;
    pymod-->pymod;
    ;
    madam-->madam;
    ;
    assigns-->assigns;
    ;
    github-enthus1ast-nimisprivateip-->github-enthus1ast-nimisprivateip;
    ;
    stopwatch-->stopwatch;
    ;
    dimscord-->dimscord;
    ;
    nim-snappy-->nim-snappy;
    ;
    rapid-->rapid;
    ;
    ao-->ao;
    ;
    github-yyoncho-json_rpc-->github-yyoncho-json_rpc;
    ;
    nimbluez-->nimbluez;
    ;
    nimgram-->nimgram;
    ;
    replim-->replim;
    ;
    euwren-->euwren;
    ;
    sections-->sections;
    ;
    sugerror-->sugerror;
    ;
    mort-->mort;
    ;
    kwin-->kwin;
    ;
    dataurl-->dataurl;
    ;
    nimagg-->nimagg;
    ;
    seccomp-->seccomp;
    ;
    enet-->enet;
    ;
    nimlibxlsxwriter-->nimlibxlsxwriter;
    ;
    segmentation-->segmentation;
    ;
    nimshell-->nimshell;
    ;
    tempdir-->tempdir;
    ;
    asciitext-->asciitext;
    ;
    github-zacharycarter-nvg-->github-zacharycarter-nvg;
    ;
    omni-->omni;
    ;
    sha1-->sha1;
    ;
    wren-->wren;
    ;
    nimclipboard-->nimclipboard;
    ;
    brainlyextractor-->brainlyextractor;
    ;
    glob-->glob;
    ;
    html2karax-->html2karax;
    ;
    llvm-->llvm;
    ;
    nimff-->nimff;
    ;
    nimwebp-->nimwebp;
    ;
    rn-->rn;
    ;
    contractabi-->contractabi;
    ;
    getr-->getr;
    ;
    choosenim-->choosenim;
    ;
    chronopipe-->chronopipe;
    ;
    mn-->mn;
    ;
    nimrpc_milis-->nimrpc_milis;
    ;
    github-yglukhov-threadpools-->github-yglukhov-threadpools;
    ;
    hpx-->hpx;
    ;
    nim_searches-->nim_searches;
    ;
    emmy-->emmy;
    ;
    imghdr-->imghdr;
    ;
    findtests-->findtests;
    ;
    nimarchive-->nimarchive;
    ;
    autonim-->autonim;
    ;
    cookiejar-->cookiejar;
    ;
    notcurses-->notcurses;
    ;
    min-->min;
    ;
    barbarus-->barbarus;
    ;
    snip-->snip;
    ;
    foreach-->foreach;
    ;
    sph-->sph;
    ;
    fastkiss-->fastkiss;
    ;
    faststack-->faststack;
    ;
    html5_canvas-->html5_canvas;
    ;
    gen-->gen;
    ;
    nimha-->nimha;
    ;
    nimgraphviz-->nimgraphviz;
    ;
    jdec-->jdec;
    ;
    numtoword-->numtoword;
    ;
    microasynchttpserver-->microasynchttpserver;
    ;
    nanim-->nanim;
    ;
    jester-->jester;
    ;
    gemini-->gemini;
    ;
    contra-->contra;
    ;
    libsvm-->libsvm;
    ;
    passgen-->passgen;
    ;
    nimdeps-->nimdeps;
    ;
    audius-->audius;
    ;
    joyent_http_parser-->joyent_http_parser;
    ;
    pronimgress-->pronimgress;
    ;
    atoz-->atoz;
    ;
    testify-->testify;
    ;
    zopflipng-->zopflipng;
    ;
    gene-->gene;
    ;
    threadproxy-->threadproxy;
    ;
    easymail-->easymail;
    ;
    eth_keys-->eth_keys;
    ;
    nio-->nio;
    ;
    github-alaviss-union-->github-alaviss-union;
    ;
    nimongo-->nimongo;
    ;
    grim-->grim;
    ;
    natu-->natu;
    ;
    validation-->validation;
    ;
    feednim-->feednim;
    ;
    moe-->moe;
    ;
    stringinterpolation-->stringinterpolation;
    ;
    blosc-->blosc;
    ;
    jq-->jq;
    ;
    hashlib-->hashlib;
    ;
    simple_vector-->simple_vector;
    ;
    nimgit2-->nimgit2;
    ;
    itn-->itn;
    ;
    cairo-->cairo;
    ;
    libnotify-->libnotify;
    ;
    mysqlparser-->mysqlparser;
    ;
    ndns-->ndns;
    ;
    variantkey-->variantkey;
    ;
    imap-->imap;
    ;
    blackvas-->blackvas;
    ;
    gnutls-->gnutls;
    ;
    jestermongopool-->jestermongopool;
    ;
    playlists-->playlists;
    ;
    hpack-->hpack;
    ;
    basic2d-->basic2d;
    ;
    nimes-->nimes;
    ;
    smbexec-->smbexec;
    ;
    snail-->snail;
    ;
    pastebin-->pastebin;
    ;
    phoon-->phoon;
    ;
    rbac-->rbac;
    ;
    gdbmc-->gdbmc;
    ;
    seq2d-->seq2d;
    ;
    litestore-->litestore;
    ;
    nimagehide-->nimagehide;
    ;
    nimcx-->nimcx;
    ;
    platformer-->platformer;
    ;
    cligen-->cligen;
    ;
    espeak-->espeak;
    ;
    omnimax-->omnimax;
    ;
    getch-->getch;
    ;
    nimgame2-->nimgame2;
    ;
    yahooweather-->yahooweather;
    ;
    golib-->golib;
    ;
    steamworks-->steamworks;
    ;
    calibre-->calibre;
    ;
    rexpaint-->rexpaint;
    ;
    xlsxio-->xlsxio;
    ;
    alignment-->alignment;
    ;
    byteutils-->byteutils;
    ;
    httpkit-->httpkit;
    ;
    vectors-->vectors;
    ;
    nish-->nish;
    ;
    gm_api-->gm_api;
    ;
    nimfm-->nimfm;
    ;
    mccache-->mccache;
    ;
    stage-->stage;
    ;
    base58-->base58;
    ;
    github-disruptek-grok-->github-disruptek-grok;
    ;
    mui-->mui;
    ;
    batteries-->batteries;
    ;
    ass-->ass;
    ;
    srt-->srt;
    ;
    termbox-->termbox;
    ;
    hts-->hts;
    ;
    asynctest-->asynctest;
    ;
    blimp-->blimp;
    ;
    watch_for_files-->watch_for_files;
    ;
    analytics-->analytics;
    ;
    eris_utils-->eris_utils;
    ;
    hnimast-->hnimast;
    ;
    runeterra_decks-->runeterra_decks;
    ;
    the_nim_alliance-->the_nim_alliance;
    ;
    libtcod_nim-->libtcod_nim;
    ;
    xors3d-->xors3d;
    ;
    siphash-->siphash;
    ;
    preprod-->preprod;
    ;
    xom-->xom;
    ;
    ndf-->ndf;
    ;
    io-egl-->io-egl;
    ;
    vmprotect-->vmprotect;
    ;
    crosscompile-->crosscompile;
    ;
    mpdclient-->mpdclient;
    ;
    foliant-->foliant;
    ;
    asyncmysql-->asyncmysql;
    ;
    nominatim-->nominatim;
    ;
    openurl-->openurl;
    ;
    simhash-->simhash;
    ;
    tmpnim-->tmpnim;
    ;
    norman-->norman;
    ;
    persistent_enums-->persistent_enums;
    ;
    qt5_qtsql-->qt5_qtsql;
    ;
    edn-->edn;
    ;
    morelogging-->morelogging;
    ;
    libssh2-->libssh2;
    ;
    arduino-->arduino;
    ;
    nestegg-->nestegg;
    ;
    daemonize-->daemonize;
    ;
    duktape-->duktape;
    ;
    extensions-->extensions;
    ;
    fastx_reader-->fastx_reader;
    ;
    stones-->stones;
    ;
    nimfcuk-->nimfcuk;
    ;
    github-thisago-findxml-->github-thisago-findxml;
    ;
    nerve-->nerve;
    ;
    kmer-->kmer;
    ;
    coco-->coco;
    ;
    sequtils2-->sequtils2;
    ;
    mutableseqs-->mutableseqs;
    ;
    nimborg-->nimborg;
    ;
    eth_trie-->eth_trie;
    ;
    crowngui-->crowngui;
    ;
    decimal-->decimal;
    ;
    cpython-->cpython;
    ;
    dotenv-->dotenv;
    ;
    pdba-->pdba;
    ;
    niprefs-->niprefs;
    ;
    egl-->egl;
    ;
    quickjwt-->quickjwt;
    ;
    awk-->awk;
    ;
    vtable-->vtable;
    ;
    github-fragworks-chipmunk7-->github-fragworks-chipmunk7;
    ;
    bs-->bs;
    ;
    shady-->shady;
    ;
    bcra-->bcra;
    ;
    nifty-->nifty;
    ;
    nimtiingo-->nimtiingo;
    ;
    shlex-->shlex;
    ;
    nimcef-->nimcef;
    ;
    allegro5-->allegro5;
    ;
    figures-->figures;
    ;
    fixmath-->fixmath;
    ;
    proxyproto-->proxyproto;
    ;
    drawim-->drawim;
    ;
    miter-->miter;
    ;
    io-sixense-->io-sixense;
    ;
    logue-->logue;
    ;
    jester2swagger-->jester2swagger;
    ;
    miniz-->miniz;
    ;
    oldgtk3-->oldgtk3;
    ;
    exprgrad-->exprgrad;
    ;
    rethinkdb-->rethinkdb;
    ;
    github-jyapayne-nimterop-->github-jyapayne-nimterop;
    ;
    bump-->bump;
    ;
    haraka-->haraka;
    ;
    eloverblik-->eloverblik;
    ;
    libgit2-->libgit2;
    ;
    nimoji-->nimoji;
    ;
    selenimum-->selenimum;
    ;
    duckduckgo-->duckduckgo;
    ;
    rect-->rect;
    ;
    stor-->stor;
    ;
    gigi-->gigi;
    ;
    dnsstamps-->dnsstamps;
    ;
    jade-nim-->jade-nim;
    ;
    arraymancer_vision-->arraymancer_vision;
    ;
    linenoise-->linenoise;
    ;
    nimwc-->nimwc;
    ;
    changer-->changer;
    ;
    tweens-->tweens;
    ;
    fileinput-->fileinput;
    ;
    regex-->regex;
    ;
    rain-->rain;
    ;
    docx-->docx;
    ;
    ruby-->ruby;
    ;
    nimjson-->nimjson;
    ;
    nimpcre-->nimpcre;
    ;
    ui-->ui;
    ;
    mofuw-->mofuw;
    ;
    wiki2text-->wiki2text;
    ;
    sixense-->sixense;
    ;
    watchout-->watchout;
    ;
    prettystr-->prettystr;
    ;
    xidoc-->xidoc;
    ;
    ssostrings-->ssostrings;
    ;
    github-disruptek-cutelog-->github-disruptek-cutelog;
    ;
    gnuplotlib-->gnuplotlib;
    ;
    untar-->untar;
    ;
    pipelines-->pipelines;
    ;
    redis-->redis;
    ;
    anime-->anime;
    ;
    shimsham-->shimsham;
    ;
    jesterwithplugins-->jesterwithplugins;
    ;
    utils-->utils;
    ;
    prettyclr-->prettyclr;
    ;
    hsluv-->hsluv;
    ;
    tissue-->tissue;
    ;
    niup-->niup;
    ;
    c2nim-->c2nim;
    ;
    github-yyoncho-asynctools-->github-yyoncho-asynctools;
    ;
    nimly-->nimly;
    ;
    drand48-->drand48;
    ;
    nimcl-->nimcl;
    ;
    smoothing-->smoothing;
    ;
    netbuff-->netbuff;
    ;
    filesize-->filesize;
    ;
    progress-->progress;
    ;
    io-serialport-->io-serialport;
    ;
    dnsprotocol-->dnsprotocol;
    ;
    georefar-->georefar;
    ;
    github-zacharycarter-nimassimp-->github-zacharycarter-nimassimp;
    ;
    jsonob-->jsonob;
    ;
    pls-->pls;
    ;
    gungnir-->gungnir;
    ;
    nimflux-->nimflux;
    ;
    redux_nim-->redux_nim;
    ;
    rollinghash-->rollinghash;
    ;
    shizuka-->shizuka;
    ;
    closure_compiler-->closure_compiler;
    ;
    nimstopwatch-->nimstopwatch;
    ;
    optionsutils-->optionsutils;
    ;
    winversion-->winversion;
    ;
    mdevolve-->mdevolve;
    ;
    noisy-->noisy;
    ;
    kissfft-->kissfft;
    ;
    sdnotify-->sdnotify;
    ;
    github-disruptek-nim-terminaltables-->github-disruptek-nim-terminaltables;
    ;
    webrod-->webrod;
    ;
    distances-->distances;
    ;
    migrate-->migrate;
    ;
    ipfshttpclient-->ipfshttpclient;
    ;
    baker-->baker;
    ;
    webrtcvad-->webrtcvad;
    ;
    paramidi_soundfonts-->paramidi_soundfonts;
    ;
    cbor-->cbor;
    ;
    trick-->trick;
    ;
    spinny-->spinny;
    ;
    binaryparse-->binaryparse;
    ;
    grab-->grab;
    ;
    usha-->usha;
    ;
    tinyfiledialogs-->tinyfiledialogs;
    ;
    logit-->logit;
    ;
    macroplus-->macroplus;
    ;
    metatag-->metatag;
    ;
    amka-->amka;
    ;
    diff-->diff;
    ;
    asyncanything-->asyncanything;
    ;
    fae-->fae;
    ;
    hats-->hats;
    ;
    awssts-->awssts;
    ;
    xgboost.nim-->xgboost.nim;
    ;
    dotprov-->dotprov;
    ;
    nimish-->nimish;
    ;
    ndbex-->ndbex;
    ;
    scinim-->scinim;
    ;
    dogapi_cli-->dogapi_cli;
    ;
    bped-->bped;
    ;
    github-haxscramper-hlibgit2-->github-haxscramper-hlibgit2;
    ;
    nimcr-->nimcr;
    ;
    slacklib-->slacklib;
    ;
    result-->result;
    ;
    halonium-->halonium;
    ;
    loony-->loony;
    ;
    coap-->coap;
    ;
    treesitter_php-->treesitter_php;
    ;
    htmlview-->htmlview;
    ;
    commandeer-->commandeer;
    ;
    hex-->hex;
    ;
    nimview-->nimview;
    ;
    camelize-->camelize;
    ;
    genode-->genode;
    ;
    luhny-->luhny;
    ;
    cppclass-->cppclass;
    ;
    bgfxdotnim-->bgfxdotnim;
    ;
    nimpb-->nimpb;
    ;
    pixels-->pixels;
    ;
    nsu-->nsu;
    ;
    dbg-->dbg;
    ;
    romanim-->romanim;
    ;
    hayaa-->hayaa;
    ;
    whip-->whip;
    ;
    datamancer-->datamancer;
    ;
    wstp-->wstp;
    ;
    spry-->spry;
    ;
    metatools-->metatools;
    ;
    faker-->faker;
    ;
    moss_nim-->moss_nim;
    ;
    pathname-->pathname;
    ;
    ioselectors-->ioselectors;
    ;
    json_serialization-->json_serialization;
    ;
    nimssl-->nimssl;
    ;
    gyaric-->gyaric;
    ;
    oblivion-->oblivion;
    ;
    notify-->notify;
    ;
    mailcow-->mailcow;
    ;
    sndfile-->sndfile;
    ;
    struct-->struct;
    ;
    github-yglukhov-android-->github-yglukhov-android;
    ;
    nimosc-->nimosc;
    ;
    receq-->receq;
    ;
    shene-->shene;
    ;
    treesitter_c_sharp-->treesitter_c_sharp;
    ;
    zero_functional-->zero_functional;
    ;
    distributions-->distributions;
    ;
    opencolor-->opencolor;
    ;
    nim_telegram_bot-->nim_telegram_bot;
    ;
    os_files-->os_files;
    ;
    base45-->base45;
    ;
    spotify-->spotify;
    ;
    unsplash-->unsplash;
    ;
    evmc-->evmc;
    ;
    gara-->gara;
    ;
    nmqtt-->nmqtt;
    ;
    eth_bloom-->eth_bloom;
    ;
    sqliteral-->sqliteral;
    ;
    nyml-->nyml;
    ;
    teafiles-->teafiles;
    ;
    batchsend-->batchsend;
    ;
    gameoflife-->gameoflife;
    ;
    tkrzw-->tkrzw;
    ;
    rcedit-->rcedit;
    ;
    shoco-->shoco;
    ;
    github-zacharycarter-freetype-->github-zacharycarter-freetype;
    ;
    brainfuck-->brainfuck;
    ;
    nimlz4-->nimlz4;
    ;
    datetime2human-->datetime2human;
    ;
    nbaser-->nbaser;
    ;
    qrcodegen-->qrcodegen;
    ;
    unchained-->unchained;
    ;
    asynctools-->asynctools;
    ;
    karax-->karax;
    ;
    stb_image-->stb_image;
    ;
    vector-->vector;
    ;
    zhsh-->zhsh;
    ;
    woocommerce-api-nim-->woocommerce-api-nim;
    ;
    xio-->xio;
    ;
    httpform-->httpform;
    ;
    at-->at;
    ;
    simple_parseopt-->simple_parseopt;
    ;
    cobs-->cobs;
    ;
    csv-->csv;
    ;
    niminst-->niminst;
    ;
    notificatcher-->notificatcher;
    ;
    spfun-->spfun;
    ;
    jestercookiemsgs-->jestercookiemsgs;
    ;
    gravatar-->gravatar;
    ;
    nim0-->nim0;
    ;
    urand-->urand;
    ;
    controlstructures-->controlstructures;
    ;
    rocksdb-->rocksdb;
    ;
    subviewer-->subviewer;
    ;
    lrparser-->lrparser;
    ;
    nimraylib_now-->nimraylib_now;
    ;
    nim_chacha20_poly1305-->nim_chacha20_poly1305;
    ;
    fnv-->fnv;
    ;
    capstone-->capstone;
    ;
    ansiwave-->ansiwave;
    ;
    unalix-->unalix;
    ;
    nimgl-->nimgl;
    ;
    jestergeoip-->jestergeoip;
    ;
    plnim-->plnim;
    ;
    supersnappy-->supersnappy;
    ;
    shaname-->shaname;
    ;
    procs-->procs;
    ;
    fontconfig-->fontconfig;
    ;
    roots-->roots;
    ;
    parsefixed-->parsefixed;
    ;
